USE [master]
GO

/****** Object:  Database [POINTDB]    Script Date: 18/04/2021 16:05:50 ******/
CREATE DATABASE [POINTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'POINTDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\POINTDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'POINTDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\POINTDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [POINTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [POINTDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [POINTDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [POINTDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [POINTDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [POINTDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [POINTDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [POINTDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [POINTDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [POINTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [POINTDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [POINTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [POINTDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [POINTDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [POINTDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [POINTDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [POINTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [POINTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [POINTDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [POINTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [POINTDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [POINTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [POINTDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [POINTDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [POINTDB] SET  MULTI_USER 
GO

ALTER DATABASE [POINTDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [POINTDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [POINTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [POINTDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [POINTDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [POINTDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [POINTDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [POINTDB] SET  READ_WRITE 
GO


